name: Push image to docker hub as artifact
on: push
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven

      - name: Build with maven
        run: mvn clean install

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to Dokerhub
        uses: docker/login-action@v1
        with:
          username: $ {{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          registry: docker.pkg.github.com



      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with: 
          context: .
          username: $ {{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          registry: docker.pkg.github.com
          push: true
          tags: suman8285/github-actions:latest